#ifndef IMPORTTDYRESULT_GLOBAL_H
#define IMPORTTDYRESULT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IMPORTTDYRESULT_LIB
# define IMPORTTDYRESULT_EXPORT Q_DECL_EXPORT
#else
# define IMPORTTDYRESULT_EXPORT Q_DECL_IMPORT
#endif

#endif // IMPORTTDYRESULT_GLOBAL_H
