#ifndef PRECORE_DATA_H_
#define PRECORE_DATA_H_


// 条目分类类型
#define TDY_PRE_CATE_UNKNOWN		0
#define TDY_PRE_CATE_BASE			1
#define TDY_PRE_CATE_FOLDER			2
#define TDY_PRE_CATE_RIGIDPART		3
#define TDY_PRE_CATE_FLEXPART		4		// deprecated, 2014.4.5,Jerry
#define TDY_PRE_CATE_MNFPART		5
#define TDY_PRE_CATE_ASSEMBLY		6
#define TDY_PRE_CATE_LOAD			7
#define TDY_PRE_CATE_MARKER			8
#define TDY_PRE_CATE_GRAPHICS		9
//#define TDY_PRE_CATE_INSTNACE		10		// deprecated, 2014.4.14, Jerry
#define TDY_PRE_CATE_PARAMETERS		11
#define TDY_PRE_CATE_STL			12
#define TDY_PRE_CATE_SHAPE			13
#define TDY_PRE_CATE_PARAMETERITEM	14
#define TDY_PRE_CATE_MOTION			15
#define TDY_PRE_CATE_JOINT			16
#define TDY_PRE_CATE_INTPAR			17
#define TDY_PRE_CATE_GROUND			18
#define TDY_PRE_CATE_FEMPART		19
#define TDY_PRE_CATE_CONTACT		20
#define TDY_PRE_CATE_REQUEST		21
#define TDY_PRE_CATE_SET			22

#define TDY_PRE_CATE_USER			500


// 条目的类类型
#define TDY_PRE_ITEMCLASS_BASEITEM	 1000
//#define TDY_PRE_ITEMCLASS_MBASEITEM	 1001
#define TDY_PRE_ITEMCLASS_ASSEMBLY   1002
#define TDY_PRE_ITEMCLASS_PARAMETERS 1003
#define TDY_PRE_ITEMCLASS_FEMPART	 1004


// 数据的类类型
#define TDY_POST_ITEMCLASS_BASE		1200
#define TDY_POST_ITEMCLASS_RIGID	1201
#define TDY_POST_ITEMCLASS_FLEX		1202
#define TDY_POST_ITEMCLASS_DYNAMICRIGID 1203



#endif