#ifndef MTSEARCHENGINE_GLOBAL_H
#define MTSEARCHENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MTSEARCHENGINE_LIB
# define MTSEARCHENGINE_EXPORT Q_DECL_EXPORT
#else
# define MTSEARCHENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // MTSEARCHENGINE_GLOBAL_H
